# Generated by Django 6.0.3 on 2026-03-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('resource_type', models.CharField(choices=[('room', 'Аудиторія'), ('lab', 'Лабораторія'), ('equipment', 'Обладнання'), ('computer_class', 'Комп’ютерний клас'), ('conference_room', 'Конференц-зала')], max_length=50, verbose_name='Тип ресурсу')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('location', models.CharField(max_length=255, verbose_name='Місцезнаходження')),
                ('capacity', models.PositiveIntegerField(default=1, verbose_name='Місткість')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Ресурс',
                'verbose_name_plural': 'Ресурси',
                'ordering': ['name'],
            },
        ),
    ]
