# Generated by Django 6.0.3 on 2026-03-22 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'Активне'), ('cancelled', 'Скасоване')], default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
