# Generated by Django 6.0.3 on 2026-03-28 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_booking_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'Вхід у систему'), ('create_booking', 'Створення бронювання'), ('cancel_booking', 'Скасування бронювання'), ('delete_booking', 'Видалення бронювання'), ('approve_booking', 'Підтвердження бронювання'), ('reject_booking', 'Відхилення бронювання')], max_length=50, verbose_name='Тип дії')),
                ('object_type', models.CharField(choices=[('user', 'Користувач'), ('resource', 'Ресурс'), ('booking', 'Бронювання'), ('system', 'Система')], max_length=50, verbose_name='Тип об’єкта')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID об’єкта')),
                ('description', models.TextField(verbose_name='Опис')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Час')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Лог дії',
                'verbose_name_plural': 'Логи дій',
                'ordering': ['-created_at'],
            },
        ),
    ]
