# Generated by Django 6.0.3 on 2026-04-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_actionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='department',
            field=models.CharField(blank=True, choices=[('ipz', 'Інженерії програмного забезпечення (ІПЗ)'), ('kn', 'Комп’ютерних наук (КН)'), ('ai', 'Штучного інтелекту (ШІ)'), ('ist', 'Інформаційних систем та технологій (ІСТ)')], max_length=20, verbose_name='Кафедра'),
        ),
    ]
